### ISSUE TITLE
Opening files in binary mode.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Tarsnap/scrypt#1]
```
I found this bug when I modified the original code to run on windows.
I have modified fopens to use binary mode in main.c .
Modified main.c is in the attachment.
```

Original issue reported on code.google.com by `doma...@gmail.com` on 4 Jan 2014 at 12:11

Attachments:
* [main.c](https://storage.googleapis.com/google-code-attachments/scrypt/issue-1/comment-0/main.c)

**Comment by cperciva** [comment]
Fixed by 665d284d.
