### ISSUE TITLE
scrypt should hint about available options

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/scrypt#11]
the "usage" doesn't give any hint that there's more options available.

**Comment by gperciva** [comment]
On second thought, maybe I should just add the options to `usage()`.  `kivaloo` and `spipe` don't provide a `--help`, and "forcing" people to read the man page isn't unreasonable for serious-use programs like `scrypt`.

**Comment by cperciva** [comment]
Yes, the `usage()` output should match the synopsis in the man page.
