### ISSUE TITLE
time is not correct

### ISSUE THREAD

**Issue by tnkmt** [Tarsnap/scrypt#139]
When I type

    $ scrypt enc -M 1073741824 -t 500 secret.txt encrypted.txt.scrypt

it takes about 2-3 minutes instead of 500 seconds on my computer.

I consider this a bug.

I am using Ubutnu, version of the scrypt utility is 1.2.0-1.

    $ sudo dpkg --list 'scrypt*'
    ...
    ii  scrypt         1.2.0-1      amd64        File encryption utility using scr

    $ uname -a
    Linux computer 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I tested decryption too, the time is not correct (less than 500 seconds).

    $ scrypt dec encrypted.txt.scrypt decrypted.txt -t 500

**Comment by gperciva** [comment]
Could you please elaborate on why you consider this a bug?  The man page clearly states:

```
     -t maxtime     Use at most maxtime seconds of CPU time to compute the
                    derived encryption key.
```

2-3 minutes is less than 500 seconds, so "Use at most" seems to be fulfilled.

**Comment by cperciva** [comment]
Along with the fact that the time is merely an approximate upper bound -- is this a system which adjusts its clock speed based on how heavily loaded it is?  (e.g., most laptops?)  It's possible that scrypt is calibrating its performance when the system is mostly idle (and running at a low clock speed) but the CPU speed increases while it's running; unfortunately there's not much scrypt can do to detect this case.

**Comment by tnkmt** [comment]
> 2-3 minutes is less than 500 seconds, so "Use at most" seems to be fulfilled.

This is not how I understand it. The cycle should stop when the `maxtime` is reached, not before.

>  It's possible that scrypt is calibrating its performance when the system is mostly idle (and running at a low clock speed) but the CPU speed increases while it's running; unfortunately there's not much scrypt can do to detect this case.

There is a way for the program to correct such error - just compare the real elapsed time with the target and if it does not match - continue for n cycles, then compare again, etc. 

If the error in time is +/- 10% it's acceptable, but 70% is too much.

**Comment by cperciva** [comment]
> There is a way for the program to correct such an error - just compare the real elapsed time with the target and if it does not match - continue for n cycles, then compare again, etc.

That's not how it works.  The scrypt algorithm needs to know its parameters before it starts computing; it can't change in the middle.

> If the error in time is +/- 10% it's acceptable, but 70% is too much.

Maybe scrypt isn't what you want then.

**Comment by tnkmt** [comment]
I have another hypothesis.

Maybe the first test of the CPU speed is with small memory requirement and the data is cached on the fast cache memory (instead of the slow RAM on the motherboard).
