### ISSUE TITLE
libscrypt

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/scrypt#146]
It might be worth adding an option to autotools to create and install a `libscrypt`, along with the relevant headers.  I see there's a few projects floating around that do this (including packages for Debian, Ubuntu, homebrew) from third-party.

**Comment by cperciva** [comment]
Yeah, maybe.  I was avoiding this because (a) there isn't really any cross-platform way to do "libraries", and (b) the scrypt code is small enough that I figured people could just import it into their codebase.

**Comment by cperciva** [comment]
Theoretically, yes.  I've heard complaints about it not working very well but I don't know if those were due to autotools being inherently broken or merely difficult to use.

**Comment by gperciva** [comment]
From offline communication: libscrypt should not include `scryptenc_*`; it should only include `crypto_scrypt()`.

**Comment by Smattr** [comment]
This would be great! I had assumed the omission of a librarised scrypt was deliberate and [patched the build system to add this](https://github.com/Smattr/passwand/blob/master/scrypt/Makefile.am.patch) (inline below for posterity), but if I could stop doing this and lean on an official upstream libscrypt I (and presumably others) certainly would.

```patch
Scrypt's build system does not expose a reusable version of crypto_scrypt(). To
work around this, the following patch adds a library that achieves this.

diff --git Makefile.am Makefile.am
index f037aa6..616c01d 100644
--- Makefile.am
+++ Makefile.am
@@ -69,6 +69,22 @@ noinst_LIBRARIES+=	libscrypt_sse2.a
 libscrypt_sse2_a_SOURCES=	lib/crypto/crypto_scrypt_smix_sse2.c
 libscrypt_sse2_a_CFLAGS=`. ./cpusupport-config.h; echo $${CFLAGS_X86_SSE2}`
 
+noinst_LIBRARIES+= libcrypto_scrypt.a
+libcrypto_scrypt_a_SOURCES= \
+			libcperciva/alg/sha256.c			\
+			libcperciva/alg/sha256.h			\
+			libcperciva/cpusupport/cpusupport_x86_sse2.c	\
+			libcperciva/util/insecure_memzero.c		\
+			libcperciva/util/insecure_memzero.h		\
+			libcperciva/util/warnp.c			\
+			libcperciva/util/warnp.h			\
+			lib/crypto/crypto_scrypt.c			\
+			lib/crypto/crypto_scrypt.h			\
+			lib/crypto/crypto_scrypt_smix.c			\
+			lib/crypto/crypto_scrypt_smix.h			\
+			lib/crypto/crypto_scrypt_smix_sse2.c			\
+			lib/crypto/crypto_scrypt_smix_sse2.h
+
 EXTRA_DIST = \
 	COPYRIGHT						\
 	FORMAT							\
```

**Comment by gperciva** [comment]
Hi @Smattr, we're moving in this direction, such as commits like https://github.com/Tarsnap/scrypt/commit/70ada72da342f4cce2dabf6b57676d100c4db500 (which might simplify your downstream patch as well).  Still a few details to work out, though.

**Comment by gperciva** [comment]
`libscrypt-kdf` is now in scrypt master.

**Comment by Smattr** [comment]
Nice work. Naive question but why is it suffixed with "kdf"? Surely I can use (misuse?) scrypt for purposes other than as a key derivation function?

**Comment by cperciva** [comment]
Two reasons:

1. Password hashing is exactly the same thing as key derivation, so the name isn't really wrong. ;-)

2. There's a whole bunch of libscrypt libraries and scrypt() functions out there, so we figured it would be helpful to avoid using the same name.
