### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by infin1tyy** [Tarsnap/scrypt#159]
I literally want to be able to use this in a C++ project and I'm finding it very difficult.
I'm new to C++ and if this was documented that would be really nice! Thanks.

**Comment by gperciva** [comment]
Hi @infin1tyy,

You can use scrypt as a library inside a C++ project just like you would use any other C library inside C++.  A quick google search suggests:
https://stackoverflow.com/questions/12066279/using-c-libraries-for-c-programs
(the url is misleading; the final part should be "C++ programs", but I guess that stackoverflow doesn't show `+` characters in urls)

**Comment by infin1tyy** [comment]
Thanks! I appreciate it.
