### ISSUE TITLE
Feature request: Specify N, r, p in the command line

### ISSUE THREAD

**Issue by mihao** [Tarsnap/scrypt#200]
There is a lot of information about what scrypt parameters are recommended at a given time for a given level of security, but there is no easy way to specify these parameters in the command line. I can specify maxmem and/or maxtime, but I won't know how safe my data is going to be, because the values of N and p depend on the state of my machine and they even change from one invocation to another (which is very confusing, by the way). Moreover, decryption may happen on a completely different machine, so maxmem and maxtime have limited usefulness anyway.

 It would be great if we could simply invoke scrypt like this:
`scrypt enc -N1048576 -r8 -p1 secret_file secret_file.scrypt`
Or perhaps this notation would be a bit more convenient:
`scrypt enc -lgN 20 -r 8 -p 1 secret_file secret_file.scrypt`

**Comment by cperciva** [comment]
I don't think it makes sense to specify `r` at the command line; the default value of `8` has been appropriate on a wide range of systems for the past decade and there's no reason to think that it will cease to be appropriate in the foreseeable future.

But setting `N` and `p` via the command line seems like it would be a useful feature.

**Comment by gperciva** [comment]
Since `N` must be a power of two, and passing large numbers on the command-line is annoying, I think it makes sense to pass `--logN` rather than `-N`.  (But it's not a firm belief, so I'm happy to be overruled.)

**Comment by gperciva** [comment]
This was added in #249.
