### ISSUE TITLE
Using scrypt in a c++ project

### ISSUE THREAD

**Issue by BFamzz** [Tarsnap/scrypt#223]
After building scrypt, what header file do I have to include to use scrypt for hashing?

**Comment by gperciva** [comment]
Did you look at the README, especially https://github.com/Tarsnap/scrypt#using-scrypt-as-a-kdf ?

**Comment by BFamzz** [comment]
@gperciva Thanks alot. I missed out the flag for installing the library. It's working fine. Thanks.
