### ISSUE TITLE
Undefined reference to crypto_scrypt

### ISSUE THREAD

**Issue by BFamzz** [Tarsnap/scrypt#224]
I am working on a c++ project and included libscrypt-kdf but when linking it throws an error. 

I included the header file as follows in my project:

`#ifdef __cplusplus 
extern "C" {
#endif
#include <string.h>
#include "scrypt-kdf.h"
#ifdef __cplusplus 
}
#endif`

Here is also my hashPassword function: 

`int hashPassword(const char* password, const char* salt, uint8_t hashedPasswordOutput[]) {
	int exitCode = scrypt_kdf((const uint8_t*)password, strlen(password),
		(const uint8_t*)salt, strlen(salt), N, r, p, hashedPasswordOutput, OUTPUT_BUFLEN);

	return exitCode;
}`

And finally, here is the error being thrown:

`/usr/bin/ld: CMakeFiles/hello_crow.dir/main.cpp.o: in function `hashPassword(char const*, char const*, unsigned char*)':
main.cpp:(.text+0x1a0e): undefined reference to `crypto_scrypt'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/hello_crow.dir/build.make:88: hello_crow] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/hello_crow.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

Here is a screenshot of the error:

![image](https://user-images.githubusercontent.com/38426051/71467088-0472ea00-27c2-11ea-881d-219a1fcdee13.png)

Kindly help please. Thanks.

**Comment by cperciva** [comment]
Sounds like you're not linking to the dynamic library.  I don't use CMake so I don't know what the syntax you need for this is.

**Comment by BFamzz** [comment]
I was able to resolve it. I included this in my CMakeLists.txt file.

`target_link_libraries(scrypt-kdf) `

Thanks.
