### ISSUE TITLE
[question] Is the scrypt algorithm quantum-resistant?

### ISSUE THREAD

**Issue by aurora-vasiliev** [Tarsnap/scrypt#305]
IBM claims to operate a 65 qubit quantum computer.
How long would it take to crack a scrypt cipher with this quantum computer right now?
How about the 1000 qubit quantum computer [promised by IBM](https://www.sciencemag.org/news/2020/09/ibm-promises-1000-qubit-quantum-computer-milestone-2023) in 2023?

**Comment by cperciva** [comment]
I am not an expert on quantum computing, but considering that scrypt uses millions of bits of state, I don't expect that quantum computers would be very useful any time soon.
