### ISSUE TITLE
Make libscrypt-kdf available to C++ applications

### ISSUE THREAD

**Issue by Emill** [Tarsnap/scrypt#363]
The [scrypt-kdf.h](https://github.com/Tarsnap/scrypt/blob/master/libscrypt-kdf/scrypt-kdf.h) header does not wrap the function using `extern "C"`, which leads to linking issues "undefined reference" in C++ applications. A workaround is to wrap the `#include <scrypt-kdf.h>` line inside `extern "C"` as explained by https://github.com/Tarsnap/scrypt/issues/224, which is a bit annoying.

It would be better to do this directly inside the scrypt-kdf.h file instead.

**Comment by gperciva** [comment]
I'm not a C++ expert, but I believe that the

```
extern "C" {
  #include "..."
}
```

syntax is the canonical way to include a C header in a C++ project.  I think it's an entirely normal part of writing code in C++.

**Comment by Emill** [comment]
Usually system libraries have these extern statements for compatibility with C++. From what I have seen, it seems more common to add these externs directly in the header file rather than requiring the application developer to add externs around the include statement. Since there are no particular downsides of having them directly in the include file but it enhances the experience for C++ developers, I guess that's why this is usually done.

As one of many examples, you have GLib, which is a C library but can be used from C++ as well. See https://stackoverflow.com/questions/58665349/what-are-g-begin-decls-and-g-end-decls-for.

The `libscrypt` project did exactly this: https://github.com/technion/libscrypt/commit/7c0ecdae2856ffe33647c5a6b54b73da6c55a9f6.

**Comment by cperciva** [comment]
I agree that this isn't really necessary; on the other hand, since the point of scrypt-kdf.h is to make it easier for people to use this code, we might as well make it easier for people to use this code.

@Emill Can you open a PR with a patch to add this?

**Comment by gperciva** [comment]
I included this fix in #364.

**Comment by Emill** [comment]
Nice! Sorry, I didn't have time myself to file a PR.

**Comment by gperciva** [comment]
Added in #364; will be part of the next release.
