### ISSUE TITLE
Feature request: Add verbose (-v) option 

### ISSUE THREAD

**Issue by coderb** [Tarsnap/scrypt#5]
It would be nice if there was a -v option that showed the parameters and/or memory/cpu settings chosen when scrypting a file.

**Comment by cperciva** [comment]
You're not the only person asking for this either.  Right now there is code for printing those settings but it's hidden behind #ifdef DEBUG.

I'm not going to have time to implement this in the near future, but it should be pretty straightforward and I'm always happy to review pull requests.

**Comment by gperciva** [comment]
Would you object to `-v` being "version" and `-V` being "verbose"?

**Comment by cperciva** [comment]
Ick, yes.  If there's an option which means "verbose" it should always be -v.  Is there a standard command line option for printing a version number aside from --version?  (We could do that, but it seems a waste to pull in getopt_long just for that...)

**Comment by gperciva** [comment]
I don't know of any standard short form of `--version`.

One advantage of using `getopt_long` is that then we could offer `--maxmem`, `maxmemfrac` and the like as well, which is easier to understand than `-M` and `-m`.

**Comment by gperciva** [comment]
Incidently, `spipe` and `spiped` both use 'v' for "print version number".  I guess you only accepted that PR because you didn't want `getopt_long` in there?

**Comment by cperciva** [comment]
Partly because I didn't want getopt_long, partly because we didn't have a "verbose" option for spiped (nor am I really sure what it would do).

Speaking of long options though, I might write an insane getopt_long replacement (see https://github.com/Tarsnap/libcperciva/issues/9).  Let me decide if I want to do that before we decide about option names here.

**Comment by cperciva** [comment]
This is now done.
