### ISSUE TITLE
Memory usage seems capped at 25%

### ISSUE THREAD

**Issue by coderb** [Tarsnap/scrypt#6]
It seems like the source code intends to cap memory usage at 50%, however on my system (debian using 1.16 svn 31) executing "scrypt enc -m 1 -t 10000 file" seems to max out at 25% of RAM (top shows 25% under VIRT column).

I did a quick test to comment out the line that limits maxmem to 0.5 and top now shows 50% of RAM used.

Is this behavior expected?

**Comment by cperciva** [comment]
scrypt attempts to use up to 50% of the "available" RAM, based on a variety of unreliable approaches for guessing how much RAM is "available".  So yes, this is expected.

**Comment by coderb** [comment]
The thing is, without my patch I could only ever get it to use 25%, even on an idle system.

**Comment by cperciva** [comment]
The other issue here is that scrypt has to use a power of 2 amount of memory.  So if you have 8 GB of RAM, but scrypt detects that 7.9 GB is available, it will decide to use up to 50% of the available RAM, i.e., 3.95 GB... and the largest power of 2 less than that is 2 GB.  So you end up with 25% of the total RAM (and 26% of the "available" RAM) being used.
