### ISSUE TITLE
OpenBSD scrypt install difficulties

### ISSUE THREAD

**Issue by jungle-boogie** [Tarsnap/scrypt#76]
Hello,

I'm attempting to install scrypt on my openbsd machine but it fails during autoreconf process.

```
git clone https://github.com/Tarsnap/scrypt
cd scrypt
autoreconf -i
```
Output:
```
aclocal:configure.ac:12: warning: macro `AM_PROG_AR' not found in library
configure.ac:12: error: possibly undefined macro: AM_PROG_AR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf-2.69: /usr/local/bin/autoconf-2.69 failed with exit status: 1
```

I have these installed: automake-1.9, autoconf-2.69 and libtool version 1.5.26. Do I need something more?

Any pointers would be greatly appreciated!

**Comment by gperciva** [comment]
Casual googling suggests that automake 1.9 was released in 2004, while AM_PROG_AR is necessary in automake 1.12 (released 2012).  I'll investigate in more depth tomorrow morning.

(also, note that if you use the official scrypt release from https://www.tarsnap.com/scrypt.html then you don't need to go through autoreconf or have the automake tools)

**Comment by jungle-boogie** [comment]
Hi @gperciva,

Thanks for the response. I think you're onto something with automake version 1.12 being necessary. I'll give that a try tomorrow if you think it's worth it.

**Comment by gperciva** [comment]
Hi @jungle-boogie,

Try the https://github.com/Tarsnap/scrypt/tree/support-obsolete-automake branch.  I suspect that it won't make onto master because we prefer to point people at the signed releases, but I'm curious about whether it helps you.

**Comment by jungle-boogie** [comment]
Hi @gperciva,

Sorry, don't know git well but below is what I did.

```
cd ~/bin
rm -rf scrypt
git clone https://github.com/Tarsnap/scrypt
cd scrypt
git checkout support-obsolete-automake
```

```
$ autoreconf -i
Provide an AUTOCONF_VERSION environment variable, please
```

```
$ autoreconf -i
Provide an AUTOMAKE_VERSION environment variable, please
autoreconf-2.69: aclocal failed with exit status: 127
```

```
$ export AUTOMAKE_VERSION=1.9
$ autoreconf -i
configure.ac: installing `config.aux/install-sh'
configure.ac: installing `config.aux/missing'
Makefile.am: C objects in subdir but `AM_PROG_CC_C_O' not in `configure.ac'
Makefile.am: installing `config.aux/compile'
Makefile.am: installing `config.aux/depcomp'
autoreconf-2.69: automake failed with exit status: 1
````

```
./configure
checking for _FILE_OFFSET_BITS value needed for large files... no
checking compiler_warnings... yes
checking CFLAGS for maximum warnings... -Wall
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in' 
```


I think I'll give up at this point and install automake 1.12+

**Comment by jungle-boogie** [comment]
> I think I'll give up at this point and install automake 1.12+

All's good with automake 1.14, installed from openbsd packages!

Thanks for the efforts put on the branch!

**Comment by gperciva** [comment]
huh, I guess there were other issues.  Oh well, thanks for checking!
